stages:
  - .pre
  - build
  - deploy

variables:
  GIT_DEPTH: 0
  GIT_STRATEGY: clone
  GIT_SUBMODULE_STRATEGY: recursive

include:
  - template: Workflows/Branch-Pipelines.gitlab-ci.yml
  - project: 'hive/common-ci-configuration'
    ref: 296649fb125e2cb3f22686f2c2bd662b19e17c72
    file:
      - '/templates/npm_projects.gitlab-ci.yml'

default:
  tags:
    - public-runner-docker

lint:
  stage: .pre
  extends: .npm_based_job_base
  script:
    - npm run lint-ci

build:
  stage: build
  extends: .npm_build_template
  variables:
    DIST_DIR: "$CI_PROJECT_DIR/dist"
    NPM_PACKAGE_SCOPE: "@hiveio"
    NPM_PACKAGE_NAME: "healthchecker-component"
  needs:
    - job: lint

deploy_dev_package:
  stage: deploy
  extends: .npm_deploy_package_template
  variables:
    NPM_PACKAGE_SCOPE: "@hiveio"
    DIST_DIR: "$CI_PROJECT_DIR/dist"
  before_script:
    - export PACKAGE_TGZ_PATH="${DIST_DIR}/$(basename ${BUILT_PACKAGE_PATH})"
    - !reference [.npm_deploy_package_template, before_script]
  needs:
    - job: build
      artifacts: true

deploy_production_public_npm:
  stage: deploy
  extends: .registry_npmjs_org_deploy_package_template
  id_tokens:
    SIGSTORE_ID_TOKEN:
      aud: sigstore
  variables:
    NPM_PUBLISH_TOKEN: "$INTERNAL_HIDDEN_PUBLISH_TOKEN"
    NPM_PACKAGE_NAME: "healthchecker-component"
    NPM_PROVENANCE_ENABLE: "0"
    DIST_DIR: "$CI_PROJECT_DIR/dist"
  before_script:
    - export PACKAGE_TGZ_PATH="${DIST_DIR}/$(basename ${BUILT_PACKAGE_PATH})"
    - !reference [.registry_npmjs_org_deploy_package_template, before_script]
  needs:
    - job: deploy_dev_package
    - job: build
      artifacts: true
