stages:
  - .pre
  - build
  - deploy

variables:
  GIT_DEPTH: 0
  GIT_STRATEGY: clone
  GIT_SUBMODULE_STRATEGY: recursive

include:
  - template: Workflows/Branch-Pipelines.gitlab-ci.yml
  - project: 'hive/common-ci-configuration'
    ref: 7b42a5584d854c2aee4b7e02cfd3de2bc4e8d77e
    file:
      - '/templates/npm_projects.gitlab-ci.yml'

default:
  tags:
    - public-runner-docker

lint:
  stage: .pre
  extends: .npm_based_job_base
  script:
    - npm run lint-ci

build:
  stage: build
  extends: .npm_build_template
  variables:
    DIST_DIR: "$CI_PROJECT_DIR/dist"
    NPM_PACKAGE_SCOPE: "@hiveio"
    NPM_PACKAGE_NAME: "healthchecker-component"
  needs:
    - job: lint

deploy_dev_package:
  stage: deploy
  extends: .npm_deploy_package_template
  variables:
    NPM_PACKAGE_SCOPE: "@hiveio"
    DIST_DIR: "$CI_PROJECT_DIR/dist"
  needs:
    - job: build
      artifacts: true

deploy_production_public_npm:
  extends:
    - .registry_npmjs_org_deploy_package_template
  stage: deploy
  variables:
    NPM_PUBLISH_TOKEN: "$INTERNAL_HIDDEN_PUBLISH_TOKEN"
    NPM_PACKAGE_NAME: "healthchecker-component"
    DIST_DIR: "$CI_PROJECT_DIR/dist"
  needs:
    - job: deploy_dev_package
    - job: build
      artifacts: true
